### ISSUE TITLE
Mailer sender not verified by SES

### ISSUE THREAD

**Issue by desmondhume** [RoxasShadow/devise_invitations#1]
Hi, 
I know this is a Amazon Ses-specific issue, but I think it could be useful for other services too.
Basically, SES complains the mail sender is not a verified email address.

https://github.com/RoxasShadow/devise_invitations/blob/master/lib/devise_invitations/mailer.rb#L4

``` ruby
def instructions(invitation)
  #...
  @sender = invitation.sent_by
  #...
end
```

How about using a configuration (maybe `Devise.mailer_sender` which is the default devise configuration)?

**Comment by RoxasShadow** [comment]
Does something like [this](https://github.com/RoxasShadow/devise_invitations/commit/730864c52ebdf8d6c24e867f6079fa301ed0c6cd) work for you?

**Comment by desmondhume** [comment]
Looks good to me! :+1:

**Comment by RoxasShadow** [comment]
Good to hear.

> Pushing gem to https://rubygems.org...
> Successfully registered gem: devise_invitations (0.2.1)
